{"content": {"suites": {"0": {"status": {"total_pass": 2, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_launch", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_url", "rerun": "0"}, "2": {"status": "FAIL", "message": "           ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000027497C48730>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=61507): Max retries exceeded with url: /session/2f98e714f440c90d8622ac90885dc093/title (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027497C48730>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))\n", "test_name": "test_title", "rerun": "0"}}, "suite_name": "test_myntra.py"}}}, "date": "September 15, 2022", "start_time": 1663212270.9645364, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "2", "fail": "1", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "3"}